set(CMAKE_CXX_STANDARD 23)  # o 20, 26
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(NOT DEFINED VCPKG_C_FLAGS)
    set(VCPKG_C_FLAGS "-fPIC")
else()
    list(APPEND VCPKG_C_FLAGS "-fPIC")
endif()

string(JOIN " " VCPKG_C_FLAGS ${VCPKG_C_FLAGS})

if(NOT DEFINED VCPKG_CXX_FLAGS)
    set(VCPKG_CXX_FLAGS "-fPIC")
else()
    list(APPEND VCPKG_CXX_FLAGS "-fPIC")
endif()

string(JOIN " " VCPKG_CXX_FLAGS ${VCPKG_CXX_FLAGS})

set(ZLIB_COMPAT ON)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR x86_64)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_SYSTEM_PROCESSOR=x86_64)
