string(APPEND VCPKG_C_FLAGS " -fPIC -Wno-maybe-uninitialized")
string(APPEND VCPKG_CXX_FLAGS " -fPIC -Wno-maybe-uninitialized")
string(APPEND VCPKG_LINKER_FLAGS " -fuse-ld=lld")

set(ZLIB_COMPAT ON)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR x86_64)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)
