set(ZLIB_COMPAT ON)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR x86_64)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_POSITION_INDEPENDENT_CODE=ON)
